# SUPPORT VECTOR MACHINE
SVM  machine learning algorithm tries to find a boundary that divides the data in such a way that the "misclassification" error can be minimized...

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#IMPORTING DATASET
bankdata=pd.read_csv("bill_authentication.csv")

In [3]:
print(bankdata.shape)
bankdata.head()

(1372, 5)


Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [4]:
#DATA PREPROCESSING
x=bankdata.drop('Class', axis=1)
y=bankdata['Class']

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.20)

In [6]:
from sklearn.svm import SVC
svclassifier=SVC(kernel='linear')
svclassifier.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [7]:
#TO MAKE PREDICTION
y_pred=svclassifier.predict(x_test)

In [8]:
#EVALUATING THE ALGORITHAM

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[151   2]
 [  1 121]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       153
           1       0.98      0.99      0.99       122

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



# KERNEL SVM
USE FOR NON_LINEAR SEPRABLE DATA,
WHERE STRAIGHT LINE CANNOT USE FOR DICISION BOUNDARYS.

TO SOLVE ALGORITHAM OF  KERNEL SVM WE USE IRIS DATASET 

In [9]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)  
irisdata.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [10]:
#PREPROCESSING
x=irisdata.drop('Class', axis=1)
y=irisdata['Class']


In [11]:
#TRAIN TEST SPLIT

from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test=train_test_split(x,y, test_size=0.20)


# POLYNOMIAL KERNEL

In [12]:
from sklearn.svm import SVC
svclassifier=SVC(kernel='poly', degree=8)
svclassifier.fit(x_train, y_train)

C:\Users\mani\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [13]:
# MAKING PRIDECTION

y_pred=svclassifier.predict(x_test)
#y

In [14]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
#print(classification_report(y_test, y_pred))  

[[14  0  0]
 [ 0  6  2]
 [ 0  2  6]]


# GAUSSIAN KERNEL

In [15]:
from sklearn.svm import SVC
svclassifier=SVC(kernel='rbf')
svclassifier.fit(x_train,y_train)

C:\Users\mani\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [16]:
#prediction and evaluation

y_pred=svclassifier.predict(x_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 

[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       1.00      0.88      0.93         8
 Iris-virginica       0.89      1.00      0.94         8

       accuracy                           0.97        30
      macro avg       0.96      0.96      0.96        30
   weighted avg       0.97      0.97      0.97        30



# sigmoid Kernel

In [18]:
from sklearn.svm import SVC
svclassifier=SVC(kernel='sigmoid')
svclassifier.fit(x_train, y_train)

C:\Users\mani\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [19]:
y_pred=svclassifier.predict(x_test)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 0,  0, 14],
       [ 0,  0,  8],
       [ 0,  0,  8]], dtype=int64)

In [21]:
print(classification_report(y_test, y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00        14
Iris-versicolor       0.00      0.00      0.00         8
 Iris-virginica       0.27      1.00      0.42         8

       accuracy                           0.27        30
      macro avg       0.09      0.33      0.14        30
   weighted avg       0.07      0.27      0.11        30



C:\Users\mani\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
# HERE WE CONCLUDE THAT OUR GAUSSIAN KERNEL IS BEST ON SEEN CONFUSION MATRIX